In [1]:
%matplotlib inline
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

%matplotlib inline
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv('dlbcl_preprocessed.txt', header = None , sep=' ' )
df.head()

0            1            2            3            4   \
0    A28102_at   766.641438   773.865121  1405.578179   998.368321   
1  AB000114_at   555.720641   422.732757   600.159750   454.351773   
2  AB000115_at   691.214533   856.915398   694.416481   761.426765   
3  AB000220_at   541.307724   499.503064   603.836309   430.826342   
4  AB000409_at  1071.146880  1011.280030  1044.097223  1374.274472   

            5            6            7            8            9   ...  \
0  1196.410368   877.489566   985.997191   797.388033  1325.268204  ...   
1   837.224699   849.100054   648.697772   426.612265   672.285031  ...   
2  1037.254172  1234.196280  1134.589229   666.814007   995.182984  ...   
3   839.575270   534.436861   670.277238   525.937466   585.678810  ...   
4  1494.958842  1056.126153  1136.099294  1077.246582  1007.712920  ...   

            68           69           70           71           72  \
0   616.894257  1239.576382   964.218278   768.828127   695.573655   
1   439.720855   701.499011   541.069495   529.532609   413.100731   
2  1386.846144   771.303028   837.186396   915.509577   624.736412   
3   636.664678   612.478206   533.529787   459.419674   422.341154   
4  1381.037726   899.483802  1253.650248  1125.612623  1040.631401   

            73           74           75           76           77  
0   715.334712  1469.582552   773.449718  1051.385520  1002.147982  
1   521.978989   864.323464   574.023235   635.089523   699.537355  
2   868.721379  1097.449801   683.639082   807.437439   913.208019  
3   545.226945   877.149345   557.992828   759.467597   606.505939  
4  1241.448009  1518.529512  1082.058385  1288.913105  1199.067588  

[5 rows x 78 columns]

In [4]:
df2 = df.head(10)

In [5]:
df2 = df2[[1,2,3]]

In [6]:
df2.head()

1            2            3
0   766.641438   773.865121  1405.578179
1   555.720641   422.732757   600.159750
2   691.214533   856.915398   694.416481
3   541.307724   499.503064   603.836309
4  1071.146880  1011.280030  1044.097223

In [7]:
df2=df2.rename( columns={1:0,2:1,3:2})

In [8]:
df2= df2.iloc[0:10]

In [9]:
df2

0            1            2
0   766.641438   773.865121  1405.578179
1   555.720641   422.732757   600.159750
2   691.214533   856.915398   694.416481
3   541.307724   499.503064   603.836309
4  1071.146880  1011.280030  1044.097223
5   792.385579   617.507703   967.313015
6   619.781103   505.821700   717.910395
7  1025.738198   655.536193   721.028208
8  2779.694245  1843.701009  2703.723537
9  1700.876595   766.059861   867.727801

In [10]:
####for original data, replace df2 by df henceward

In [11]:
m=[]
m= df2.max()

In [12]:
lt = len(df2)
f_l=len(df2.columns)

In [13]:
m

0    2779.694245
1    1843.701009
2    2703.723537
dtype: float64

In [14]:
l=[]
l= df2.min()

In [15]:
l

0    541.307724
1    422.732757
2    600.159750
dtype: float64

In [91]:
#alter for perfection
k=[]
k=(m-l)/20

In [92]:
k

0    111.919326
1     71.048413
2    105.178189
dtype: float64

In [93]:
mat = [[-1 for i in range(f_l)] for j in range(lt)]

In [94]:
len(mat[0])

3

In [95]:
original = df2.as_matrix(columns=None)

In [96]:
len(original[0])

3

In [97]:
original[5]

array([792.38557863, 617.50770318, 967.31301474])

In [98]:
lt

10

In [99]:
#for g1 only

for i in range(lt):
    for j in range (f_l):
        if original[i][j] >= original[0][j] - k[j]  and original[i][j] <= original[i][0] + k[j]:
            mat[i][j] = 1
        

In [100]:
dist = [[[0 for k1 in range(f_l)] for j in range(lt)] for i in range(lt)]

In [101]:
%%time

#k1 traverses through each gene as g1, g2,..
#i traverses through individual gene as g11, g12 or correlation with g1 
#j is for the different parameters

for k1 in range (lt):    
    for i in range(lt):
        for j in range (f_l):
            if original[i][j] >= original[k1][j] - k[j]  and original[i][j] <= original[k1][j] + k[j]:
                dist[k1][i][j] = 1
 

CPU times: user 4.16 ms, sys: 28 µs, total: 4.19 ms
Wall time: 4.14 ms


In [102]:
tot_clu =[]
tot_clu1 =[]
for i in range(len(dist)) :
    point_clu = []
    point_clu1 = []
    for j in range(len(dist[i])):
        if np.sum(dist[i][j]) == 3 :
            point_clu.append(original[j])
            point_clu1.append(j)
    tot_clu.append(point_clu)
    tot_clu1.append(point_clu1)

In [103]:
list_2 = [x for x in tot_clu if x]
list_21 = [x for x in tot_clu1 if x]

In [104]:
# Modified QuickSort
# Given a set of clustures, sorts according to the length of clustures


def partition(arr,low,high): 
    i = ( low-1 )         # index of smaller element 
    pivot = arr[high]     # pivot 
  
    for j in range(low , high): 
  
        # If current element is smaller than or 
        # equal to pivot 
        if   len(arr[j]) <= len(pivot) : 
          
            # increment index of smaller element 
            i = i+1 
            arr[i],arr[j] = arr[j],arr[i] 
  
    arr[i+1],arr[high] = arr[high],arr[i+1] 
    return ( i+1 ) 
  
# The main function that implements QuickSort 
# arr[] --> Array to be sorted, 
# low  --> Starting index, 
# high  --> Ending index 
  
# Function to do Quick sort 
def quickSort(arr,low,high): 
    if low < high: 
  
        # pi is partitioning index, arr[p] is now 
        # at right place 
        pi = partition(arr,low,high) 
  
        # Separately sort elements before 
        # partition and after partition 
        quickSort(arr, low, pi-1) 
        quickSort(arr, pi+1, high)

In [105]:
test = tot_clu1

In [106]:
%%time

n = len(test) 
quickSort(test,0,n-1)

CPU times: user 17 µs, sys: 4 µs, total: 21 µs
Wall time: 24.1 µs


In [107]:
test.reverse()

In [108]:
list2 = [x for x in test]

In [109]:
simi_th = 0.9


In [110]:
list2

[[9], [8], [7], [6], [5], [4], [3], [2], [1], [0]]

In [111]:
test

[[9], [8], [7], [6], [5], [4], [3], [2], [1], [0]]

In [112]:
#cluster with first element

list2[0]

[9]

In [113]:
###2-d clustering
clu = []
clu.append(list2[0])
for i in range(1,len(list2)):
    clu_new = list2[i]
    common_elements = list(set().union(*clu) & set(clu_new))
    simi = len(common_elements)/len(clu_new)
    clu_nei = list(set(clu_new) - set(common_elements))
    if simi < simi_th :
        clu.append(clu_nei)
    else :
        clu[-1] = clu[-1] + clu_nei

In [114]:
tot_clu =[]

for i in range(len(clu)) :
    point_clu = []    
    for j in range(len(clu[i])):
        k=clu[i][j]
        point_clu.append(original[k])            
    tot_clu.append(point_clu)
    

In [40]:
##k==10% of range
tot_clu

[[array([555.72064097, 422.73275651, 600.15975046]),
  array([541.3077239 , 499.50306431, 603.83630852]),
  array([619.781103  , 505.82170024, 717.91039461])],
 [array([1700.87659454,  766.05986062,  867.72780114])],
 [array([2779.69424516, 1843.70100856, 2703.72353709])],
 [array([1025.73819756,  655.53619304,  721.02820762])],
 [array([792.38557863, 617.50770318, 967.31301474])],
 [array([1071.14687964, 1011.28003013, 1044.09722329])],
 [array([691.21453309, 856.91539828, 694.41648112])],
 [array([ 766.64143788,  773.86512115, 1405.57817931])]]

In [65]:
##k==20% of range
tot_clu

[[array([555.72064097, 422.73275651, 600.15975046]),
  array([691.21453309, 856.91539828, 694.41648112]),
  array([541.3077239 , 499.50306431, 603.83630852]),
  array([792.38557863, 617.50770318, 967.31301474]),
  array([619.781103  , 505.82170024, 717.91039461]),
  array([1025.73819756,  655.53619304,  721.02820762])],
 [array([1071.14687964, 1011.28003013, 1044.09722329])],
 [array([ 766.64143788,  773.86512115, 1405.57817931])],
 [array([1700.87659454,  766.05986062,  867.72780114])],
 [array([2779.69424516, 1843.70100856, 2703.72353709])]]

In [90]:
##k==33.33% of range
tot_clu

[[array([ 766.64143788,  773.86512115, 1405.57817931]),
  array([555.72064097, 422.73275651, 600.15975046]),
  array([691.21453309, 856.91539828, 694.41648112]),
  array([541.3077239 , 499.50306431, 603.83630852]),
  array([1071.14687964, 1011.28003013, 1044.09722329]),
  array([792.38557863, 617.50770318, 967.31301474]),
  array([619.781103  , 505.82170024, 717.91039461]),
  array([1025.73819756,  655.53619304,  721.02820762]),
  array([1700.87659454,  766.05986062,  867.72780114])],
 [array([2779.69424516, 1843.70100856, 2703.72353709])]]

In [115]:
##k==5% of range
tot_clu

[[array([1700.87659454,  766.05986062,  867.72780114])],
 [array([2779.69424516, 1843.70100856, 2703.72353709])],
 [array([1025.73819756,  655.53619304,  721.02820762])],
 [array([619.781103  , 505.82170024, 717.91039461])],
 [array([792.38557863, 617.50770318, 967.31301474])],
 [array([1071.14687964, 1011.28003013, 1044.09722329])],
 [array([541.3077239 , 499.50306431, 603.83630852])],
 [array([691.21453309, 856.91539828, 694.41648112])],
 [array([555.72064097, 422.73275651, 600.15975046])],
 [array([ 766.64143788,  773.86512115, 1405.57817931])]]